dist: xenial
branches:
  only:
    - master
language: csharp
solution: eform-appointmentBase/Microting.AppointmentBase.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build Microting.AppointmentBase.sln
  - dotnet test -v n Microting.AppointmentBase.Unit.Tests/Microting.AppointmentBase.Unit.Tests.csproj
  - export GITVERSION=`git describe --abbrev=0 --tags | cut -d "v" -f 2`
  - echo $GITVERSION
  - dotnet pack Microting.AppointmentBase.sln -c Release -o ./artifacts -p:PackageVersion=$GITVERSION
  - export FILENAME="/home/travis/build/microting/eform-appointmentBase/Microting.AppointmentBase/artifacts/Microting.AppointmentBase.${GITVERSION}.nupkg"
  - echo $FILENAME
  - dotnet nuget push $FILENAME -k $NUGET_SECRET_KEY -s https://api.nuget.org/v3/index.json || true
