dist: xenial
branches:
  only:
    - master
language: csharp
solution: eform-appointmentBase/Microting.AppointmentBase.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build Microting.AppointmentBase.sln
  - dotnet test -v n Microting.AppointmentBase.Unit.Tests/Microting.AppointmentBase.Unit.Tests.csproj
